/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import gradel.Parse;
import org.junit.Test;
import static org.junit.Assert.*;

public class parseTest {
    @Test public void testAppHasAGreeting() {
        gradel.Parse classUnderTest = new Parse();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
